# Site settings
title: Liu wei
email: i@liuwei.co
url: https://liuweicode.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: liu wei
  location: Location
  social: Around the Web
  credits: Donate

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/liuweisays
  - title: github
    url: http://github.com/liuweicode

# Postal address (add as many lines as necessary)
address:
  - line: Room 1201,Building No.33,LinFenMingCheng
  - line: ZhaBei District ShangHai City

# Credits content
credits: 'Thank you for your support! <br/><br/> <img src="img/alipay.JPG" width="120" height="120"/>'

# Build settings
markdown: kramdown
permalink: pretty
